$(document).ready(function(){
    $("#img-show").click(function(){
        $("#design").toggle();
    });
    $("#dev-show").click(function(){
        $("#dev-hide").toggle();
    });
    $("#product-show").click(function(){
        $("#product-hide").toggle();
    });
});